-- COMMENTS

-- Organization members can create comments on tasks
-- belonging to their organization.
create policy "Users can create comments in their organization tasks"
on public.comments
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.tasks
    join public.projects
      on projects.id = tasks.project_id
    join public.organization_members
      on organization_members.organization_id = projects.organization_id
    where tasks.id = comments.task_id
      and organization_members.user_id = (select auth.uid())
  )
);


-- Users can update only their own comments.
create policy "Users can update their own comments"
on public.comments
for update
to authenticated
using (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.tasks
    join public.projects
      on projects.id = tasks.project_id
    join public.organization_members
      on organization_members.organization_id = projects.organization_id
    where tasks.id = comments.task_id
      and organization_members.user_id = (select auth.uid())
  )
)
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.tasks
    join public.projects
      on projects.id = tasks.project_id
    join public.organization_members
      on organization_members.organization_id = projects.organization_id
    where tasks.id = comments.task_id
      and organization_members.user_id = (select auth.uid())
  )
);


-- Users can delete their own comments.
-- Organization owners/admins can also delete comments.
create policy "Users can delete their own comments"
on public.comments
for delete
to authenticated
using (
  (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.tasks
      join public.projects
        on projects.id = tasks.project_id
      join public.organization_members
        on organization_members.organization_id = projects.organization_id
      where tasks.id = comments.task_id
        and organization_members.user_id = (select auth.uid())
    )
  )
  or
  exists (
    select 1
    from public.tasks
    join public.projects
      on projects.id = tasks.project_id
    join public.organization_members
      on organization_members.organization_id = projects.organization_id
    where tasks.id = comments.task_id
      and organization_members.user_id = (select auth.uid())
      and organization_members.role in ('owner', 'admin')
  )
);


-- ATTACHMENTS

-- Organization members can create attachment records
-- for tasks in their organization.
create policy "Organization members can create task attachments"
on public.attachments
for insert
to authenticated
with check (
  uploaded_by = (select auth.uid())
  and exists (
    select 1
    from public.tasks
    join public.projects
      on projects.id = tasks.project_id
    join public.organization_members
      on organization_members.organization_id = projects.organization_id
    where tasks.id = attachments.task_id
      and organization_members.user_id = (select auth.uid())
  )
);


-- Uploaders can delete their own attachments.
-- Organization owners/admins can also delete attachments.
create policy "Users can delete task attachments"
on public.attachments
for delete
to authenticated
using (
  (
    uploaded_by = (select auth.uid())
    and exists (
      select 1
      from public.tasks
      join public.projects
        on projects.id = tasks.project_id
      join public.organization_members
        on organization_members.organization_id = projects.organization_id
      where tasks.id = attachments.task_id
        and organization_members.user_id = (select auth.uid())
    )
  )
  or
  exists (
    select 1
    from public.tasks
    join public.projects
      on projects.id = tasks.project_id
    join public.organization_members
      on organization_members.organization_id = projects.organization_id
    where tasks.id = attachments.task_id
      and organization_members.user_id = (select auth.uid())
      and organization_members.role in ('owner', 'admin')
  )
);


-- NOTIFICATIONS

-- Users can update only their own notifications.
-- This will mainly be used to mark notifications as read.
create policy "Users can update their own notifications"
on public.notifications
for update
to authenticated
using (
  user_id = (select auth.uid())
)
with check (
  user_id = (select auth.uid())
);


-- Users can delete their own notifications.
-- Notifications are treated as a disposable personal inbox.
create policy "Users can delete their own notifications"
on public.notifications
for delete
to authenticated
using (
  user_id = (select auth.uid())
);


-- No client INSERT policy.
-- Notifications are generated by trusted server-side logic
-- when application events require them.


-- ACTIVITY LOG
-- No client INSERT / UPDATE / DELETE policies.
-- Activity logs should be generated by trusted server-side logic.